function perf=init_perf()

    perf.velocity=[];
    perf.rpm=[];
    perf.dbeta=[];
    perf.thrust=[];
    perf.q=[];
    perf.pshaft=[];
    perf.volts=[];
    perf.amps=[];
    perf.effmotor=[];
    perf.effprop=[];
    perf.adv=[];
    perf.ct=[];
    perf.cp=[];
    perf.dv=[];
    perf.eff=[];
    perf.pelec=[];
    perf.pprop=[];
    perf.clavg=[];
    perf.cdavg=[];